/*
 * generated by Xtext
 */
package rslingo.rsl.ui.contentassist

import rslingo.rsl.ui.contentassist.AbstractRslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RslProposalProvider extends AbstractRslProposalProvider {
}
