/*
 * generated by Xtext
 */
package rslingo.rsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RslUiModule extends rslingo.rsl.ui.AbstractRslUiModule {
	public RslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
