/*
 * generated by Xtext
 */
package rslingo.rsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import rslingo.rsl.ui.internal.RslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RslActivator.getInstance().getInjector(RslActivator.RSLINGO_RSL_RSL);
	}
	
}
