/*
 * generated by Xtext
 */
package rslingo.rsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return rslingo.rsl.ui.internal.RslActivator.getInstance().getInjector("rslingo.rsl.Rsl");
	}
	
}
