/*
 * generated by Xtext
 */
package rslingo.rsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RslRuntimeModule extends rslingo.rsl.AbstractRslRuntimeModule {

}
