/*
 * generated by Xtext
 */
package rslingo.rsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RslStandaloneSetup extends RslStandaloneSetupGenerated{

	public static void doSetup() {
		new RslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

