/**
 * generated by Xtext
 */
package rslingo.rsl.validation;

import rslingo.rsl.validation.AbstractRslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RslValidator extends AbstractRslValidator {
}
